version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
      - "./server_files:/server_files"
    environment:
      EULA: "TRUE"
      WORLD: "/server_files/world.zip"
      VERSION: "SNAPSHOT"
      # FORCE_WORLD_COPY: "TRUE" -- Force world copy from WORLD variable
      ONLINE_MODE: "false"
      SERVER_NAME: "Server de Nico"
      MOTD: "A Snapshot Minecraft Nico Server powered by Docker"
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "TRUE"
    restart: always
